# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NcpNuke < Formula
  desc "NCP Sub Account Mass Management & Resource Nuke CLI"
  homepage "https://github.com/enbraining/ncp-nuke"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.0.7/ncp-nuke_1.0.7_darwin_amd64.tar.gz"
      sha256 "983714b0c32d698930b1d8c1239c82724f3204150bcf6e37b9d1851db36c3bf9"

      def install
        bin.install "ncp-nuke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.0.7/ncp-nuke_1.0.7_darwin_arm64.tar.gz"
      sha256 "dffd5b0bdf96e7e89b4cf1f02105195e513259d5be9880e6ade31ff776c73bc5"

      def install
        bin.install "ncp-nuke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.0.7/ncp-nuke_1.0.7_linux_amd64.tar.gz"
      sha256 "06ce5a79201ed94bba1c6f7f6e252ca39b52430a90398f3234d9606b5f90761b"
      def install
        bin.install "ncp-nuke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.0.7/ncp-nuke_1.0.7_linux_arm64.tar.gz"
      sha256 "31b6d2167936013dbf17298448b1b11cc36ca5a038c53fdbed5f611b56ee2d71"
      def install
        bin.install "ncp-nuke"
      end
    end
  end
end
