# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NcpNuke < Formula
  desc "NCP Sub Account Mass Management & Resource Nuke CLI"
  homepage "https://github.com/enbraining/ncp-nuke"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.1.2/ncp-nuke_1.1.2_darwin_amd64.tar.gz"
      sha256 "bde37a9f974b8634a398dbd6375c687b08de7cc388df0c220217ad139f5d9fd7"

      def install
        bin.install "ncp-nuke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.1.2/ncp-nuke_1.1.2_darwin_arm64.tar.gz"
      sha256 "5a60e1af88f125d0c1ca1d2e4045fd22683c49dcb52db295b98af5430294306a"

      def install
        bin.install "ncp-nuke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.1.2/ncp-nuke_1.1.2_linux_amd64.tar.gz"
      sha256 "cc8ccc59e69d37a56dd14067b2444e9ceddd31e39bb95bbef06115c708c8b3eb"
      def install
        bin.install "ncp-nuke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enbraining/ncp-nuke/releases/download/v1.1.2/ncp-nuke_1.1.2_linux_arm64.tar.gz"
      sha256 "093d659968c2bc967f055f88dda9373bcb0497f2713d9f52b185a3d3e432c318"
      def install
        bin.install "ncp-nuke"
      end
    end
  end
end
